email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fresnograpestakeyard.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
repository: fresnograpestakeyard/fresnograpestakeyard.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]