name: "Update Ruby Dependencies"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to update'
        required: true
        default: 'master'

jobs:
  update-gems:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Check if branch is master
        if: ${{ github.event.inputs.branch == 'master' }}
        run: |
          echo "Cannot run on master branch"
          exit 1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true

      - name: Update all dependencies
        run: bundle update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update ruby dependencies"
          branch: ${{ github.event.inputs.branch }}
          file_pattern: Gemfile.lock
